version: "3"
services:

  language-toolbox:
    container_name: language-toolbox
    build: .
    volumes:
      - type: bind
        source: /var/run/docker.sock
        target: /var/run/docker.sock

  https-portal:
    image: steveltn/https-portal
    ports:
      - '80:80'
      - '443:443'
    links:
      - language-toolbox
    restart: always
    environment:
      DOMAINS: "language-toolbox.clickmcr.com"
      STAGE: "production"
    volumes:
      - ./ssl.conf.erb:/var/lib/nginx-conf/language-toolbox.clickmcr.com.ssl.conf.erb:ro
      - https-portal-data:/var/lib/https-portal
    # healthcheck:
    #   test: ["CMD", "service", "nginx", "status"]
    #   interval: 30s
    #   timeout: 20s
    #   retries: 3

volumes:
  https-portal-data:
